### PR TITLE
Pydarshan MiB

### PR DESCRIPTION
**Pull request by Lcjacobpd**
Replaced 2**20 approximation with 1048576 for MiB conversion

### CODE REVIEW

**Comment by Lcjacobpd** [comment]
Should make more sense now that I'm pointed at the right branch on your fork.

**Comment by Lcjacobpd** [comment]
@nawtrey could you also review this? Should be a simple merge, but I'd like to play it safe.

**Comment by nawtrey** [comment]
I don't have any comments here, pretty straightforward change. LGTM

**Comment by nawtrey** [comment]
I jumped the gun on this one -- locally the tests are failing after making this change. 

Specifically:
```
FAILED tests/test_data_access_by_filesystem.py::test_plot_data_shared_x_axis
```

I'll dig into this.

**Pull request merged**
